### PR TITLE
Added ResponseError, ShutdownResponse.

### PR DESCRIPTION
**Pull request by KalitaAlexey**
I need it to implement proper shutdown in RLS.

### CODE REVIEW

**Comment by Marwes** [comment]
The types as defined is not part of the language server protocol but is actually just a part of jsonrpc-2.0 itself. See for instance https://github.com/rust-lang-nursery/rls/blob/db07d336e13e563802692887fc79b3abf9f9db37/src/server.rs#L461 (which would make the result simply

```json
{ "jsonrpc": "2.0", "id": 123, "result": "undefined (any value here)" }
```
)

**Comment by KalitaAlexey** [comment]
@Marwes,
Actually they are.
It is described in the protocol, isn't it?

**Comment by Marwes** [comment]
Nope, https://github.com/Microsoft/language-server-protocol/blob/20cc22ec7abb26c21959a95c5cca1cd8a0fa2d54/protocol.md#shutdown-request defines the shutdown response as having an undefined result. Compare it to the show message response which is defined to return a result of a `MessageActionItem` https://github.com/Microsoft/language-server-protocol/blob/20cc22ec7abb26c21959a95c5cca1cd8a0fa2d54/protocol.md#showmessage-request.

**Comment by KalitaAlexey** [comment]
@Marwes,
But it also defined the error field.

**Comment by Marwes** [comment]
See section 5 of http://www.jsonrpc.org/specification. The error field is what is defined if an error is return, result is defined on success.

**Comment by KalitaAlexey** [comment]
@Marwes,
Thank you for explanation.
I didn't know that.

**Pull request closed without merging**
