### PR TITLE
Add related information support to  TextDocumentClientCapabilities

### PR DESCRIPTION
**Pull request by Xanewok**
Followup to #56.

r? @Marwes

### CODE REVIEW

**Comment by Xanewok** [comment]
Merging, thanks!

**Comment by Marwes** [comment]
@Xanewok I sent you an invite on crates.io as well (not sure if I forgot to do it earlier or if I sent it and it expired before) so you should be able to do a release, otherwise I will make one tonight.

**Comment by Xanewok** [comment]
@Marwes done - published 0.40. That was my first release on crates.io, I hope everything was done correctly!

**Comment by autozimu** [comment]
I noticed tag v0.40.0 is not pushed to github.

I would recommend to install https://github.com/sunng87/cargo-release. And the release process should be as easy as `cargo release --level minor`.

**Comment by Xanewok** [comment]
Pushed the missing tag. Will install cargo-release, thanks for recommending it!

**Pull request merged**
