### PR TITLE
Adding more CompletionItemKind.

### PR DESCRIPTION
**Pull request by autozimu**
Affects https://github.com/autozimu/LanguageClient-neovim/issues/287

### CODE REVIEW

**Comment by Marwes** [comment]
It might be a good idea to add a `Other(int)` variant which captures any unrecognized integers. But on the other hand that opens up the possibility of this for all other `enum`s as well which feels wrong... The protocol is not very clear whether adding more variants to "enums" like this are breaking or not.

**Comment by autozimu** [comment]
I'd prefer it fail fast.

If we add this extra variant, we will never get notified new variant are added in protocol and is missing in this lib.

**Comment by Marwes** [comment]
Well the problem is that users are the ones encountering the breakage :/ Also, the spec says in https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#textdocumentclientcapabilities-define-capabilities-the-editor--tool-provides-on-text-documents that the client can specify which values it can handle and if this is specified it should also handle other variants gracefully (same thing for `SymbolKind`). There isn't a way that I can see to handle this without a case to capture unknown values.

```
completionItemKind?: {
			/**
			 * The completion item kind values the client supports. When this
			 * property exists the client also guarantees that it will
			 * handle values outside its set gracefully and falls back
			 * to a default value when unknown.
			 *
			 * If this property is not present the client only supports
			 * the completion items kinds from `Text` to `Reference` as defined in
			 * the initial version of the protocol.
			 */
			valueSet?: CompletionItemKind[];
		},
```

As long as we are diligent about updating it shouldn't matter that much though I guess.

**Comment by Marwes** [comment]
(To be clear I am not trying to push this work on you :P just wanted to have a discussion since I remembered this special case)

**Comment by autozimu** [comment]
Hmm, make sense.

**Pull request merged**
