### PR TITLE
Make WorkspaceEdit compatible with protocol 3.0.

### PR DESCRIPTION
**Pull request by autozimu**
Note: the SerdeUrl/Serde<Url> can be replaced by Url once
https://github.com/servo/rust-url/issues/304 is merged in.

### CODE REVIEW

**Comment by autozimu** [comment]
Affects https://github.com/autozimu/LanguageClient-neovim/issues/217

**Comment by Marwes** [comment]
Thanks! I added a commit in #36 to restore the explicit url_map serialization to avoid exposing the wrapper. Since I had already done the work for the non-option map and this is the only place that it is used I just changed it to work on Option<Map<...>>.

**Comment by Marwes** [comment]
Released as 0.21.0

**Comment by autozimu** [comment]
Make sense. Thanks.

**Pull request closed without merging**
