### PR TITLE
CompletionResponse could be null.

### PR DESCRIPTION
**Pull request by autozimu**
https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#completion-request-leftwards_arrow_with_hook

### CODE REVIEW

**Comment by autozimu** [comment]
Ideally it would be better to have another variant in `CompletionResponse` to represent the `null` case. But I don't know how to achieve it easily.

**Comment by Marwes** [comment]
👍 I don't beleive you have accepted the invite for crates.io? You should be able to find it by logging in with your github account on crates.io if you want to try and publish a new version?

**Comment by autozimu** [comment]
Ah, didn't know I have to accept on crates.io side.

Accepted and will do a publish soon.

Thanks.

**Comment by autozimu** [comment]
Done.

By the way, I've found [cargo release](https://github.com/autozimu/LanguageClient-neovim/blob/next/Cargo.toml#L31) has been really helpful in the process of bumping version and publishing. Here is an example config https://github.com/autozimu/LanguageClient-neovim/blob/8b0604c076b6ea8d7ad38d6c2d2352876399c0c1/Cargo.toml#L31-L37

Will allocate some time to automate the publish.

**Comment by Marwes** [comment]
Yeah that is a good idea. I have looked into it from time to time but haven't really used it since multi crate repos aren't supported (which would be where I really need it). So I have just used a shell script instead.

**Pull request merged**
